services:
  oracle-app:
    environment:
      DELPHI_CONFIG: /workspace/config/oracle.pi.yaml
    extra_hosts:
      - host.docker.internal:host-gateway
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped

  kiwix:
    volumes:
      - ./data/library/zim:/data/zim:ro
